/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.spider.bean;

public class ArticleVO {

    public long id; // required
    public String title; // required
    public String summary; // required
    public String content; // required
    public int viewCount; // required
    public String originalUrl; // required
    public long channelId; // required
    public long sourceId; // required
    public int commentFlag; // required
    public int status; // required
    public int orderWeight; // required
    public long similarArticleId; // required
    public String publishAt; // required
    public String createdAt; // required
    public String updatedAt; // required
    public String cover; // required
    public String allPics; // required
    public String sourceName; // required
    public String picType; // required
    public long recommendChannel; // required
    public int springBreezeRecommend; // required
    public String channelName; // required
    public int level; // required
    public double score; // required
    public String scoreItem; // required
    public int commentCount; // required
    public String showModel; // required
    public String guidance; // required

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public int getViewCount() {
        return viewCount;
    }

    public void setViewCount(int viewCount) {
        this.viewCount = viewCount;
    }

    public String getOriginalUrl() {
        return originalUrl;
    }

    public void setOriginalUrl(String originalUrl) {
        this.originalUrl = originalUrl;
    }

    public long getChannelId() {
        return channelId;
    }

    public void setChannelId(long channelId) {
        this.channelId = channelId;
    }

    public long getSourceId() {
        return sourceId;
    }

    public void setSourceId(long sourceId) {
        this.sourceId = sourceId;
    }

    public int getCommentFlag() {
        return commentFlag;
    }

    public void setCommentFlag(int commentFlag) {
        this.commentFlag = commentFlag;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public int getOrderWeight() {
        return orderWeight;
    }

    public void setOrderWeight(int orderWeight) {
        this.orderWeight = orderWeight;
    }

    public long getSimilarArticleId() {
        return similarArticleId;
    }

    public void setSimilarArticleId(long similarArticleId) {
        this.similarArticleId = similarArticleId;
    }

    public String getPublishAt() {
        return publishAt;
    }

    public void setPublishAt(String publishAt) {
        this.publishAt = publishAt;
    }

    public String getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    public String getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }

    public String getCover() {
        return cover;
    }

    public void setCover(String cover) {
        this.cover = cover;
    }

    public String getAllPics() {
        return allPics;
    }

    public void setAllPics(String allPics) {
        this.allPics = allPics;
    }

    public String getSourceName() {
        return sourceName;
    }

    public void setSourceName(String sourceName) {
        this.sourceName = sourceName;
    }

    public String getPicType() {
        return picType;
    }

    public void setPicType(String picType) {
        this.picType = picType;
    }

    public long getRecommendChannel() {
        return recommendChannel;
    }

    public void setRecommendChannel(long recommendChannel) {
        this.recommendChannel = recommendChannel;
    }

    public int getSpringBreezeRecommend() {
        return springBreezeRecommend;
    }

    public void setSpringBreezeRecommend(int springBreezeRecommend) {
        this.springBreezeRecommend = springBreezeRecommend;
    }

    public String getChannelName() {
        return channelName;
    }

    public void setChannelName(String channelName) {
        this.channelName = channelName;
    }

    public int getLevel() {
        return level;
    }

    public void setLevel(int level) {
        this.level = level;
    }

    public double getScore() {
        return score;
    }

    public void setScore(double score) {
        this.score = score;
    }

    public String getScoreItem() {
        return scoreItem;
    }

    public void setScoreItem(String scoreItem) {
        this.scoreItem = scoreItem;
    }

    public int getCommentCount() {
        return commentCount;
    }

    public void setCommentCount(int commentCount) {
        this.commentCount = commentCount;
    }

    public String getShowModel() {
        return showModel;
    }

    public void setShowModel(String showModel) {
        this.showModel = showModel;
    }

    public String getGuidance() {
        return guidance;
    }

    public void setGuidance(String guidance) {
        this.guidance = guidance;
    }
}

