/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.spider.bean;

public class Fetch{

  public long id; // required
  public long fetchFrequence; // required
  public long lastFetchAt; // required
  public int fetchStatus; // required
  public int fetchType; // required
  public String fetchInfo; // required
  public long sourceId; // required
  public String fetchError; // required

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getFetchFrequence() {
        return fetchFrequence;
    }

    public void setFetchFrequence(long fetchFrequence) {
        this.fetchFrequence = fetchFrequence;
    }

    public long getLastFetchAt() {
        return lastFetchAt;
    }

    public void setLastFetchAt(long lastFetchAt) {
        this.lastFetchAt = lastFetchAt;
    }

    public int getFetchStatus() {
        return fetchStatus;
    }

    public void setFetchStatus(int fetchStatus) {
        this.fetchStatus = fetchStatus;
    }

    public int getFetchType() {
        return fetchType;
    }

    public void setFetchType(int fetchType) {
        this.fetchType = fetchType;
    }

    public String getFetchInfo() {
        return fetchInfo;
    }

    public void setFetchInfo(String fetchInfo) {
        this.fetchInfo = fetchInfo;
    }

    public long getSourceId() {
        return sourceId;
    }

    public void setSourceId(long sourceId) {
        this.sourceId = sourceId;
    }

    public String getFetchError() {
        return fetchError;
    }

    public void setFetchError(String fetchError) {
        this.fetchError = fetchError;
    }
}

