/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.spider.bean;


public class SourceVO{

  public long id; // required
  public String name; // required
  public String intro; // required
  public String sourceUrl; // required
  public String iconInfo; // required
  public int subscribeCount; // required
  public long channelId; // required
  public int orderWeight; // required
  public int level; // required
  public int status; // required
  public int recommendFlag; // required
  public long createdAt; // required
  public long updatedAt; // required
  public long lastFetchAt; // required
  public long fetchFrequence; // required
  public String channelName; // required
  public int fetchType; // required
  public int fetchStatus; // required
  public String fetchInfo; // required
  public String fetchName; // required
  public int online; // required

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIntro() {
        return intro;
    }

    public void setIntro(String intro) {
        this.intro = intro;
    }

    public String getSourceUrl() {
        return sourceUrl;
    }

    public void setSourceUrl(String sourceUrl) {
        this.sourceUrl = sourceUrl;
    }

    public String getIconInfo() {
        return iconInfo;
    }

    public void setIconInfo(String iconInfo) {
        this.iconInfo = iconInfo;
    }

    public int getSubscribeCount() {
        return subscribeCount;
    }

    public void setSubscribeCount(int subscribeCount) {
        this.subscribeCount = subscribeCount;
    }

    public long getChannelId() {
        return channelId;
    }

    public void setChannelId(long channelId) {
        this.channelId = channelId;
    }

    public int getOrderWeight() {
        return orderWeight;
    }

    public void setOrderWeight(int orderWeight) {
        this.orderWeight = orderWeight;
    }

    public int getLevel() {
        return level;
    }

    public void setLevel(int level) {
        this.level = level;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public int getRecommendFlag() {
        return recommendFlag;
    }

    public void setRecommendFlag(int recommendFlag) {
        this.recommendFlag = recommendFlag;
    }

    public long getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(long createdAt) {
        this.createdAt = createdAt;
    }

    public long getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(long updatedAt) {
        this.updatedAt = updatedAt;
    }

    public long getLastFetchAt() {
        return lastFetchAt;
    }

    public void setLastFetchAt(long lastFetchAt) {
        this.lastFetchAt = lastFetchAt;
    }

    public long getFetchFrequence() {
        return fetchFrequence;
    }

    public void setFetchFrequence(long fetchFrequence) {
        this.fetchFrequence = fetchFrequence;
    }

    public String getChannelName() {
        return channelName;
    }

    public void setChannelName(String channelName) {
        this.channelName = channelName;
    }

    public int getFetchType() {
        return fetchType;
    }

    public void setFetchType(int fetchType) {
        this.fetchType = fetchType;
    }

    public int getFetchStatus() {
        return fetchStatus;
    }

    public void setFetchStatus(int fetchStatus) {
        this.fetchStatus = fetchStatus;
    }

    public String getFetchInfo() {
        return fetchInfo;
    }

    public void setFetchInfo(String fetchInfo) {
        this.fetchInfo = fetchInfo;
    }

    public String getFetchName() {
        return fetchName;
    }

    public void setFetchName(String fetchName) {
        this.fetchName = fetchName;
    }

    public int getOnline() {
        return online;
    }

    public void setOnline(int online) {
        this.online = online;
    }
}

